name: pkg

on:
  push:
    branches: [ dev-cli ]
  pull_request:
    branches: [ dev-cli ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install library
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Test with unittest
        run: python -m unittest discover -s ./src/tests

